services:
  ip-changer:
    restart: always
    image: hetzner-ip-changer
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - hetzner_ip_changer_network
    links: 
      - redis_db

  redis_db:
    restart: always
    image: redis:6.2-alpine
    command: redis-server --port 6379 --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - hetzner_ip_changer_network

  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./cert:/cert
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "444:443"
    depends_on:
      - ip-changer
    networks:
      - hetzner_ip_changer_network
    links:
      - ip-changer

networks:
  hetzner_ip_changer_network:
    driver: bridge
    internal: false

volumes:
  cache:
    driver: local
